# Use this to skip checks that incur high costs or break Free Tier eligibility
skip-check:
  # Lambda-specific skips
  - CKV_AWS_116 # Ensure Lambda has DLQ (Optional, skip if you don't want SQS costs)
  - CKV_AWS_117 # Ensure Lambda is in VPC (Avoids $32/mo NAT Gateway)
  - CKV_AWS_173 # Check encryption for env variables (Avoids $1/mo KMS fee)
  - CKV_AWS_272 # Validate code-signing (Complex setup, unnecessary for small projects)
  - CKV_AWS_27  # Ensure SQS is encrypted (Avoids KMS monthly fees)
  - CKV_AWS_115 # Skip AWS Lambda function is configured for function-level concurrent execution limit (Check not relevant for cost)

  # S3-specific skips
  - CKV_AWS_145 # S3 Default Encryption with KMS (Avoids $1/mo KMS fee)
  - CKV_AWS_18  # S3 Access Logging (Saves on request/storage costs)
  - CKV_AWS_144 # Cross-Region Replication (Prevents doubling storage costs)
  - CKV2_AWS_62 # Ensure S3 buckets should have event notifications enabled (Ensure lambda triggers are local intentionally)

  # CloudWatch-specific skips
  - CKV_AWS_158 # CloudWatch Log Group KMS Encryption (Avoids $1/mo KMS fee)
  - CKV_AWS_338  # Log retention 1 year (Stick to 7 days for cost optimization)

  # iam-specific skips
  - CKV_AWS_273 # Ensure access is controlled through SSO and not AWS IAM users (Out of Scope / Safe to Skip)
  - CKV_AWS_149 # Ensure Secrets Manager secret is encrypted using KMS CMK (Concerns Out of Scope (Cost))
  - CKV2_AWS_57 # Ensure Secrets Manager secrets should have automatic rotation enabled (Valid Security Concern, but Out of Scope)
