formatter: "markdown table"

# header-from: README.template.md # Looks for this in each folder if it exists
recursive:
  enabled: true
  path: modules
  include-main: true

sections:
  hide: [providers] # You can hide providers if you want a cleaner look

output:
  file: README.md
  mode: replace

content: |-
  {{ .Content }}
